config/routes.rb
Rails.application.routes.draw do
  get 'greeter/hello'
  get 'greeter/goodbye'
  get '/', to: 'greeter#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    get_name_and_time
    @times_displayed ||= 0  # Este operador ( ||= ) pondrá el valor de la derecha a una nueva variable de la izquierda o dejará el valor de la variable de la izquierda si esta ya existía
    @times_displayed += 1
  end

  def goodbye
    get_name_and_time
  end

  private
  
  def get_name_and_time
    random_names = ["Verónica", "Julio", "Peluchosa"]
    @name = random_names.sample
    @time = Time.now
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    # Time string in AM/PM format
    time.strftime("%I:%M%p")
  end
end

app/views/greeter/goodbye.html.erb
<h1>Greeter#goodbye</h1>
<h2>See you later <%= @name %> </h2>
<p>The time now is <%= formatted_time(@time) %> </p>
<p>Find me in app/views/greeter/hello.html.erb</p>

<p></p>
<p><%= link_to "Google MX", "https://www.google.com.mx/" %></p>
<p><%= link_to "Hello section", greeter_hello_url %>  </p>

app/views/greeter/hello.html.erb
<h1>Greeter#hello</h1>
<h2>Greetings <%= @name %> </h2>
<p>The time now is <%= formatted_time(@time) %> </p>
<p>Times "hello" have been rendered <%= @times_displayed %> </p>
<p>Find me in app/views/greeter/hello.html.erb</p>

<p></p>
<p><%= link_to "Google MX", "https://www.google.com.mx/" %></p>
<p><%= link_to "Goodbye section", greeter_goodbye_path %>  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>